//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeforeWatch.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Comment1 { get; set; }
        public int Score { get; set; }
        public int UserID { get; set; }
        public int FilmSeriesID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual FilmSeries FilmSeries { get; set; }
        public virtual User User { get; set; }
    }
}
